### PR TITLE
Enable prefixing grid by default

### PR DESCRIPTION
**Pull request by yepninja**

### CODE REVIEW

**Comment by jonathantneal** [comment]
@ai, this PR changes the default functionality of Autoprefixer. You have disabled grid prefixing, and I think it’s best preset-env follow the Autoprefixer defaults. Do you have a different opinion and would like to see this merged?

**Comment by ai** [comment]
We disabled Grid since it is polyfill with some polyfill limits.

I think Grid fits perfectly `postcss-preset-env` polyfill’s nature.

**Comment by jonathantneal** [comment]
@ai, thanks. Okay, last question — are there any other “polyfill” features that I should enable by default?

**Comment by ai** [comment]
Nope. All other things are enabled by default. Grid was the only such special prefix with limits.

**Comment by jonathantneal** [comment]
Okay. Forgive the delay, but I wanted to better understand the problem. I reviewed https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/, https://github.com/postcss/autoprefixer/issues/603, and https://github.com/postcss/autoprefixer/issues/925.

Thanks, @yepninja. This looks legit and helpful in certain instances. I actually have a few issues open for various IE support.

**Comment by ai** [comment]
@jonathantneal this article by @rachelandrew is very outdated. Unfortunately, she doesn’t want to write a note to article and article continue to mislead users :( Sad that CSS community is so unwelcome for tool authors.

**Comment by ai** [comment]
Issue https://github.com/postcss/autoprefixer/issues/603 was implemented a year ago. For this year we added many new properties including even `grid-template-area` and `grid-gap`.

You must follow `@autoprefixer` in Twitter :). Most of tweets for this year was about step by step improving Grid support.

https://github.com/postcss/autoprefixer/releases/tag/7.2.0
https://github.com/postcss/autoprefixer/releases/tag/8.3.0
https://github.com/postcss/autoprefixer/releases/tag/8.5.0

**Comment by Nemo64** [comment]
there might be overlap with this polyfill:
https://github.com/jonathantneal/postcss-gap-properties

**Comment by jonathantneal** [comment]
@yepninja, it looks like an npm failure, so I’m re-running your tests.

@ai, I’d really like to talk about this more. We can fork the issue or talk in private if you prefer. Could you be more specific about the “CSS community”? I haven’t experienced hostility, but you wouldn’t be the first or even second person to tell me they feel hostility within the CSS community 
— between CSS evangelists who embrace tools and those who seem to slight them.

This is important to me because one of the goals of this project is to soberly embrace tools, giving developers the best chance to code effectively, while giving CSS evangelists and spec authors a chance to observe and adjust the paths being formed before formalizing them.

> The web platform should develop, describe and test new high-level features, and allow web developers to iterate on them before they become standardized. This creates a virtuous cycle between standards and developers.
> — https://extensiblewebmanifesto.org/

**Comment by ai** [comment]
@jonathantneal I wrote you to a Gitter. Thanks for the support.

Right now I am preparing the talk about how CSS evangelists and CSS community block tools innovation.

**Comment by jonathantneal** [comment]
@Nemo64, according to https://github.com/postcss/autoprefixer/releases/tag/8.5.0 we are safe, because autoprefixer runs last. If you concur, I will merge this.

**Comment by jensimmons** [comment]
I remember when Autoprefixer automatically prefixed CSS Grid with code for Internet Explorer. I spent many, many months teaching people how to disable Autoprefixer line-by-line in their CSS.

I was very relieved when the defaults where changed and Autoprefixer stopped prefixing CSS Grid. It meant I could finally recommend Autoprefixer again, without lots of explanation. And I could start using it again in my own projects. (I had stopped because the labor required to eliminate Grid code line by line was not worth it to me.)

I find this very surprising, that you all want to switch the default back to 'on' again. 

Vender prefixes cannot make the 2010 version of the Grid specification magically work like the 2016 version. It's impossible to use any CSS, including prefixed CSS, to make IE understand CSS Grid code. If Autoprefixer begins making such a promise again, it will break numerous websites that have already shipped (if they rerun with a newer version of Autoprefixer, without going through a layout rewrite). 

At this point, it seems the decision to merge this patch is just being considered as retribution against Rachel Andrew. Which I do not understand at all. 

> Sad that CSS community is so unwelcome for tool authors.
> Bad example for more popular person could block innovation :(

These are deeply offensive comments. I see no evidence that the "CSS community" is holding back innovation. Are you familiar with Rachel's work? She has done nothing to push the web into a wholly new world. I cannot see any reason to be talking about her or her work like this. I find this ridiculous. 

Please do not merge this patch. I'm telling you, as one of a tiny handful of people who has taught CSS Grid to thousand of people in person, and tens of thousands online, this is a bad idea. 

If this happens, I will likely recommend people stop using Autoprefixer altogether.

**Comment by jonathantneal** [comment]
Hi, I’m super convinced to **not** merge this PR. @yepninja, thank you for taking the time to write it — PRs are my absolute favorite way to communicate suggestions — and I sincerely hope you continue contributing here.

I considered merging this because I was under the impression that autoprefixer only ever prefixes things that are wholly equivalent leaning forward. I’m not merging this because enabling this option would appear to break that expectation, which would then miscommunicate major expectations of _this_ project. I had trouble figuring this out on my own, but thankfully @rachelandrew and @jensimmons were persistent enough to provide the evidence I needed.

Now, I’m the one who asked @ai about the whole CSS community thing before I noticed folks being tagged. It’s very important to me that we squash the tribalism and backtalk perceptions of hostility or vendettas. The accusations must stop. Any initially perceived hostility was just personality, not genuine animosity. And if I had merged this, it wouldn’t be because I dislike anyone. I would have merged it because **I make mistakes all the time**, and because you fine people weren’t here to stop me. This project **needs** people like you. I don’t work on autoprefixer. I’m not a member of the CSSWG. I don’t work for a browser vendor. I’m not paid to work on open source.

I’m sorry if I suck at this, but thank you for taking the time to help me.

You might be the authors of tools and specs and talks that other people look up to when Houdini takes off, so please don’t write each other off. Be excellent to each other.

**Pull request closed without merging**
